### ISSUE TITLE
Use a configuration file for portal data

### ISSUE THREAD

**Issue by dbrnz** [ABI-Software/mapcore-integrated-webapp#4]
[main.js](https://github.com/ABI-Software/data-portal/blob/develop/map_core/app/src/main.js) of the portal app contains a number of hard-coded references to data objects, in particular in `selectionCallback()` and `initialiseMain()`. Of these, the URI to identify the flatmap **will** change after the code freeze; I don't know about the others.

How about having a `config.json` file that specifies the URIs/paths of the various data objects, that is loaded when the app starts?? [views.py](https://github.com/ABI-Software/data-portal/blob/develop/map_core/views.py) would need something like the following added to it:
```
@map_core_blueprint.route('config')
def config():
    filename = os.path.join(map_core_blueprint.root_path, 'config', 'config.json')
    return send_file(filename)
```
`config.json` should be seen as `data`, not frozen code.

Thoughts @alan-wu, @hsorby, @nickerso, @Tehsurfer??

**Comment by hsorby** [comment]
Can you give an example of how the flatmap URI will change?  From what to what.
Will we have different locations on different machines for these resources? Or are they changing for everyone?

**Comment by dbrnz** [comment]
The flatmap URI is a unique identifier giving the exact version of the PPT that the map has been generated from. This URI is the same for everyone.

As the current flatmap is revised this URI will change. Revisions in the pipeline include:
1. Adding more organ system layers along with appropriate feature annotation, as discussed yesterday.
2. Correcting object display order in the current map.
3. Correcting annotation errors in the current map.
4. Adding more pathways to the map, which PH is working on while he's flying.

Items 1, 2 and 3 will have been completed by sometime tomorrow; item 4 depends on receiving an updated PPT and will then likely go through one or two revisions (in response to feedback from subject experts). There may also be more tweaks to annotation.

**Comment by nickerso** [comment]
Talking with @alan-wu , it sounds like the other hard-coded references are temporary and will be removed. So it is just the flatmaps that we need to have. Given the aim to have the portal show any available flatmaps, does it make sense to find the flatmap URI via the KB rather than a config file? This would allow us to update the version and add other flatmaps and have the show up in the portal "automatically".

**Comment by dbrnz** [comment]
I like the idea of using the KB to find the current flatmap for a species (or other selection criteria).

The portal app could then have a flatmap selection list, defaulting to "human" -- what are the best ontological identifiers to use  for "human" and other species? There also needs to be code (outside of the flatmap viewer), called during portal initialisation and whenever the selection list is changed, to query the KB for a flatmap's URI.

At the moment, with just the one flatmap, there is no need for a selection list (simply hard-code "human") but the query still needs to be made.

**Comment by nickerso** [comment]
For ISAN there will also be some version of non-human flatmap - hopefully pig and rat.

**Comment by dbrnz** [comment]
Then:
1. The portal app will need a selection list, with prompts say of "Human", "Pig", and "Rat" that map to values in a suitable ontology of species.
2. The KB will need to contain statements like:
```
species:ID <has_flatmap> <uri_for_flatmap> .
```
3. Portal code will need to query the KB to find the selected flatmap's URI, prior to calling `loadMap` to display it.

**Comment by dbrnz** [comment]
Hmm, how about the [Vertebrate Species Ontology](https://gitlab.com/phenoscape/vto)??

**Comment by dbrnz** [comment]
This ontology is included in EMBL-EBI's Ontology Lookup Service. "Human" is [VTO:0011993](https://www.ebi.ac.uk/ols/ontologies/vto/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0011993).

**Comment by nickerso** [comment]
To keep consistency across MAPcore, we'll use the NCBI taxonomy...

**Comment by dbrnz** [comment]
Closing this as points raised have now been addressed, in particular by serving all map content remotely, not via the data portal.
